# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcCalc_pb2 as grpcCalc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpcCalc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransactionID = channel.unary_unary(
                '/ppd.MinerService/GetTransactionID',
                request_serializer=grpcCalc__pb2.Empty.SerializeToString,
                response_deserializer=grpcCalc__pb2.TransactionIDResponse.FromString,
                _registered_method=True)
        self.GetChallenge = channel.unary_unary(
                '/ppd.MinerService/GetChallenge',
                request_serializer=grpcCalc__pb2.TransactionIDRequest.SerializeToString,
                response_deserializer=grpcCalc__pb2.ChallengeResponse.FromString,
                _registered_method=True)
        self.GetTransactionStatus = channel.unary_unary(
                '/ppd.MinerService/GetTransactionStatus',
                request_serializer=grpcCalc__pb2.TransactionIDRequest.SerializeToString,
                response_deserializer=grpcCalc__pb2.TransactionStatusResponse.FromString,
                _registered_method=True)
        self.SubmitChallenge = channel.unary_unary(
                '/ppd.MinerService/SubmitChallenge',
                request_serializer=grpcCalc__pb2.SubmitChallengeRequest.SerializeToString,
                response_deserializer=grpcCalc__pb2.SubmitChallengeResponse.FromString,
                _registered_method=True)
        self.GetWinner = channel.unary_unary(
                '/ppd.MinerService/GetWinner',
                request_serializer=grpcCalc__pb2.TransactionIDRequest.SerializeToString,
                response_deserializer=grpcCalc__pb2.WinnerResponse.FromString,
                _registered_method=True)
        self.GetSolution = channel.unary_unary(
                '/ppd.MinerService/GetSolution',
                request_serializer=grpcCalc__pb2.TransactionIDRequest.SerializeToString,
                response_deserializer=grpcCalc__pb2.SolutionResponse.FromString,
                _registered_method=True)


class MinerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTransactionID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransactionID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionID,
                    request_deserializer=grpcCalc__pb2.Empty.FromString,
                    response_serializer=grpcCalc__pb2.TransactionIDResponse.SerializeToString,
            ),
            'GetChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChallenge,
                    request_deserializer=grpcCalc__pb2.TransactionIDRequest.FromString,
                    response_serializer=grpcCalc__pb2.ChallengeResponse.SerializeToString,
            ),
            'GetTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionStatus,
                    request_deserializer=grpcCalc__pb2.TransactionIDRequest.FromString,
                    response_serializer=grpcCalc__pb2.TransactionStatusResponse.SerializeToString,
            ),
            'SubmitChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitChallenge,
                    request_deserializer=grpcCalc__pb2.SubmitChallengeRequest.FromString,
                    response_serializer=grpcCalc__pb2.SubmitChallengeResponse.SerializeToString,
            ),
            'GetWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWinner,
                    request_deserializer=grpcCalc__pb2.TransactionIDRequest.FromString,
                    response_serializer=grpcCalc__pb2.WinnerResponse.SerializeToString,
            ),
            'GetSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSolution,
                    request_deserializer=grpcCalc__pb2.TransactionIDRequest.FromString,
                    response_serializer=grpcCalc__pb2.SolutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ppd.MinerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ppd.MinerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MinerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTransactionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/GetTransactionID',
            grpcCalc__pb2.Empty.SerializeToString,
            grpcCalc__pb2.TransactionIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/GetChallenge',
            grpcCalc__pb2.TransactionIDRequest.SerializeToString,
            grpcCalc__pb2.ChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/GetTransactionStatus',
            grpcCalc__pb2.TransactionIDRequest.SerializeToString,
            grpcCalc__pb2.TransactionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/SubmitChallenge',
            grpcCalc__pb2.SubmitChallengeRequest.SerializeToString,
            grpcCalc__pb2.SubmitChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/GetWinner',
            grpcCalc__pb2.TransactionIDRequest.SerializeToString,
            grpcCalc__pb2.WinnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppd.MinerService/GetSolution',
            grpcCalc__pb2.TransactionIDRequest.SerializeToString,
            grpcCalc__pb2.SolutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
