# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_calc.proto\x12\x03ppd\";\n\x0e\x43omputeRequest\x12\x13\n\x02op\x18\x01 \x01(\x0e\x32\x07.ppd.Op\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\"?\n\x0f\x43omputeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x0b\n\x03\x65rr\x18\x02 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x03 \x01(\t*7\n\x02Op\x12\r\n\tOP_UNSPEC\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x07\n\x03SUB\x10\x02\x12\x07\n\x03MUL\x10\x03\x12\x07\n\x03\x44IV\x10\x04\x32\x43\n\x0b\x43\x61lcService\x12\x34\n\x07\x43ompute\x12\x13.ppd.ComputeRequest\x1a\x14.ppd.ComputeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OP']._serialized_start=150
  _globals['_OP']._serialized_end=205
  _globals['_COMPUTEREQUEST']._serialized_start=24
  _globals['_COMPUTEREQUEST']._serialized_end=83
  _globals['_COMPUTERESPONSE']._serialized_start=85
  _globals['_COMPUTERESPONSE']._serialized_end=148
  _globals['_CALCSERVICE']._serialized_start=207
  _globals['_CALCSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
