# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x03ppd\"\x07\n\x05\x45mpty\".\n\x14TransactionIDRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"/\n\x15TransactionIDResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\"&\n\x11\x43hallengeResponse\x12\x11\n\tchallenge\x18\x01 \x01(\x05\"+\n\x19TransactionStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"U\n\x16SubmitChallengeRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\")\n\x17SubmitChallengeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"#\n\x0eWinnerResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"G\n\x10SolutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\x32\xac\x03\n\x0cMinerService\x12:\n\x10GetTransactionID\x12\n.ppd.Empty\x1a\x1a.ppd.TransactionIDResponse\x12\x41\n\x0cGetChallenge\x12\x19.ppd.TransactionIDRequest\x1a\x16.ppd.ChallengeResponse\x12Q\n\x14GetTransactionStatus\x12\x19.ppd.TransactionIDRequest\x1a\x1e.ppd.TransactionStatusResponse\x12L\n\x0fSubmitChallenge\x12\x1b.ppd.SubmitChallengeRequest\x1a\x1c.ppd.SubmitChallengeResponse\x12;\n\tGetWinner\x12\x19.ppd.TransactionIDRequest\x1a\x13.ppd.WinnerResponse\x12?\n\x0bGetSolution\x12\x19.ppd.TransactionIDRequest\x1a\x15.ppd.SolutionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_TRANSACTIONIDREQUEST']._serialized_start=32
  _globals['_TRANSACTIONIDREQUEST']._serialized_end=78
  _globals['_TRANSACTIONIDRESPONSE']._serialized_start=80
  _globals['_TRANSACTIONIDRESPONSE']._serialized_end=127
  _globals['_CHALLENGERESPONSE']._serialized_start=129
  _globals['_CHALLENGERESPONSE']._serialized_end=167
  _globals['_TRANSACTIONSTATUSRESPONSE']._serialized_start=169
  _globals['_TRANSACTIONSTATUSRESPONSE']._serialized_end=212
  _globals['_SUBMITCHALLENGEREQUEST']._serialized_start=214
  _globals['_SUBMITCHALLENGEREQUEST']._serialized_end=299
  _globals['_SUBMITCHALLENGERESPONSE']._serialized_start=301
  _globals['_SUBMITCHALLENGERESPONSE']._serialized_end=342
  _globals['_WINNERRESPONSE']._serialized_start=344
  _globals['_WINNERRESPONSE']._serialized_end=379
  _globals['_SOLUTIONRESPONSE']._serialized_start=381
  _globals['_SOLUTIONRESPONSE']._serialized_end=452
  _globals['_MINERSERVICE']._serialized_start=455
  _globals['_MINERSERVICE']._serialized_end=883
# @@protoc_insertion_point(module_scope)
